language: ruby
rvm:
- 2.3.3
script: rake test
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
#after_sucess: rake deploy
sudo: false # route your build to the container-based infrastructure for a faster build
